project:
  type: website

website:
  title: "The Joy of String Art"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: patterns/index.qmd
        text: Patterns
      - about.qmd

format:
  html:
    # theme:
    #   light:
    #     - cosmo
    #     - _theme/theme.scss
    #   dark:
    #     - cosmo
    #     - _theme/theme-dark.scss

    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



